name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  
env:
  BUILD_TYPE: Release
  BUILD_TESTS: ON

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: With OpenCV
      uses: rayandrew/with-opencv-action@v1
    
    - name: configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=${{env.BUILD_TESTS}}
      
    - name: make
      run: make
      
    - name: test
      working-directory: ${{github.workspace}}/build
      run: make test          
